name: Unit tests
  
on:
  push:
  pull_request:
    branches: [ master ]
    
jobs:
    
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd test/unit
          python -m unittest test_my_utils

  run_print_fires_func_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd test/func
          bash test_print_fires.sh
          bash test_get_data.sh
        
  run_hist_func_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          activate-environment: swe4s
      - run: |
          cd test/func
          bash test_hist.sh


  style_check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          activate-environment: swe4s
      - run: |
          pycodestyle .
          

  run_all_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          environment-name: swe4s
      - run: |
          cd test/unit
          python -m unittest test_my_utils
          cd ../func
          bash test_print_fires.sh
          bash test_get_data.sh
          bash test_hist.sh
          pycodestyle .