name: Unit tests

on:
  push:
  pull_request:
    branches: [ master ]
    
jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd test/unit
          python -m unittest test_my_utils          
  run_func_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd test/func
          bash test_print_fires.sh
          
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: |
          pycodestyle .
          
  run_all_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd test/unit
          python -m unittest test_utils
          cd ../func
          bash test_print_fires.sh
          cd
          pycodestyle print_fires.py
          